/* User Action Types */
export const USER = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT: "LOGOUT",

  ADD_INTERESTS: "ADD_INTERESTS",
  ADD_INTERESTS_SUCCESS: "ADD_INTERESTS_SUCCESS",
  ADD_INTERESTS_FAILURE: "ADD_INTERESTS_FAILURE",

  GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE: "GET_USER_INFO_FAILURE",

  CHANGE_THEME: "CHANGE_THEME",
}

/* Messages Action Types */
export const MESSAGES = {
  GET_QUESTION_SUGGESTIONS: "GET_QUESTION_SUGGESTIONS",
  GET_QUESTION_SUGGESTIONS_SUCCESS: "GET_QUESTION_SUGGESTIONS_SUCCESS",
  GET_QUESTION_SUGGESTIONS_FAILURE: "GET_QUESTION_SUGGESTIONS_FAILURE",

  GET_MESSAGES: "GET_MESSAGES",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_FAILURE: "GET_MESSAGES_FAILURE",

  ASK_QUESTION: "ASK_QUESTION",
  ASK_QUESTION_SUCCESS: "ASK_QUESTION_SUCCESS",
  ASK_QUESTION_FAILURE: "ASK_QUESTION_FAILURE",

  SELECT_QUESTION: "SELECT_QUESTION",
  SELECT_QUESTION_SUCCESS: "SELECT_QUESTION_SUCCESS",
  SELECT_QUESTION_FAILURE: "SELECT_QUESTION_FAILURE",

  SET_SELECTED_QUESTION: "SET_SELECTED_QUESTION",
}

/* Common Action Types */
export const COMMON = {
  SET_HANDLE_ALERT: "SET_HANDLE_ALERT",
}