/* User Action Types */
export const USER = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT: "LOGOUT",

  ADD_INTERESTS: "ADD_INTERESTS",
  ADD_INTERESTS_SUCCESS: "ADD_INTERESTS_SUCCESS",
  ADD_INTERESTS_FAILURE: "ADD_INTERESTS_FAILURE",

  GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE: "GET_USER_INFO_FAILURE",

  CHANGE_THEME: "CHANGE_THEME",
}

/* Messages Action Types */
export const MESSAGES = {
}