/* Auth Action Types */
export const USER = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  ADD_INTERESTS: "ADD_INTERESTS",
  ADD_INTERESTS_SUCCESS: "ADD_INTERESTS_SUCCESS",
  ADD_INTERESTS_FAILURE: "ADD_INTERESTS_FAILURE",

  GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE: "GET_USER_INFO_FAILURE",

  CHANGE_THEME: "CHANGE_THEME",
}

export const CHAT = {
}

/* User Action Types */
export const HANDLE_USER = 'HANDLE_USER'
export const HANDLE_LOGIN_DATA = 'HANDLE_LOGIN_DATA'

/* Common Action Types */
export const HANDLE_UTIL_ALERT = 'HANDLE_UTIL_ALERT'
export const HANLE_SELECTED_THEME = 'HANLE_SELECTED_THEME'

/* Questions User Action Types */
export const HANDLE_SELECTED_QUESTIONS_HOME = 'HANDLE_SELECTED_QUESTION_HOME'
